name: Build & lint project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Set up PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 7.4.27
          tools: composer:v2
      - name: Install composer.json
        run: composer install
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install frontend dependencies
        run: cd ./themes/ && yarn install
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv